### ISSUE TITLE
Banned and CD Hash File content cannot be read

### ISSUE THREAD

**Issue by ConnorDoesDev** [BomberFish/Whitelist#1]
![image](https://user-images.githubusercontent.com/69979824/218266684-83fc6f37-2e63-4345-9465-eb501f66e702.jpeg)

Info:
iPhone 12 mini
iOS 16.1.1

App installed via SideStore, could this be the issue?

**Comment by AbdullahMPrograms** [comment]
same issue here, 11 pro max IOS 16.1.2

**Comment by gygys** [comment]
I also encountered the same situation, but what is the use of the following two functions, can anyone tell me？

**Comment by bomberfish** [comment]
This is completely normal. The next update will hide these fields if the files do not exist on your device.
