### ISSUE TITLE
Virus in Whiteliste app

### ISSUE THREAD

**Issue by EfremchickEga** [BomberFish/Whitelist#10]
Hello please tell me is this virus or no?
![Screenshot_20240529-092734_Chrome](https://github.com/BomberFish/Whitelist/assets/171117162/95804bf7-75fa-438d-bf4a-beef055cac9b)
![Screenshot_20240529-092754_Chrome](https://github.com/BomberFish/Whitelist/assets/171117162/6b634244-8700-4264-84b1-135d237477dc)

**Comment by bomberfish** [comment]
why are you on android?
