### ISSUE TITLE
Can this software support ios Shortcuts?

### ISSUE THREAD

**Issue by nightwhite** [BomberFish/Whitelist#2]
My iPhone13 has several apps that won't open every day. I must cover it with WhiteList every day, so I want to ask if you can add the function of the ios instruction,I can cover with WhiteList  at regular intervals.

**Comment by bomberfish** [comment]
I might consider adding support for Shortcuts, however automatic background refresh is planned in an upcoming update.

**Comment by nightwhite** [comment]
Alright, thank you very much
