### ISSUE TITLE
My signed apps crashes

### ISSUE THREAD

**Issue by camposs0** [BomberFish/Whitelist#4]
I have an iPhone XR on 16.1.2
A few weeks ago, everything was working absolutely fine

But suddenly the certificate got 100% revoked and it didn't show me that error "Unable to verify", it just instantly crashes when I opened

I use E-Sign to install my apps and I import my revoked certificate in there 
Even when I use your app to fix blacklist, it just crashes (only the whitelist app is sideloaded with apple id)
I already tried to re-install the Whitelist app and my apps (inc E-Sign)
Tried to reboot and didnt work

pls help :(

**Comment by bomberfish** [comment]
At this moment, Whitelist can only fix blacklists, not revokes. 
Since the old certificate got revoked, you can use [this certificate](https://github.com/BomberFish/Whitelist/files/10855312/China.Huaneng.Group.zip). (Password is AppleP12.com)
