### ISSUE TITLE
Only able to overwrite blacklist but not the "internet connection" popup

### ISSUE THREAD

**Issue by MDX-Tom** [BomberFish/Whitelist#5]
Sorry to bother, although a few days ago the blacklist override works as a charm, today all of my enterprise apps seems to not open at all (no popup when pressed in the homescreen, but exits right after it starts) even after I press the Apply button in this app..
In the settings app, I see the same "internet connection is needed to verify" popup as is shown in the README file of this repository. Pressing the "verify" button does not affect at all.
![D386D645-EC25-4191-9C43-4A1598F2179C](https://user-images.githubusercontent.com/6468993/222151864-fd6a5e18-f14b-46af-bec4-9bced72b291b.jpeg)

**Comment by nightwhite** [comment]
证书撤销了 就不管用了

**Comment by FoKit** [comment]
iPhone 14 Pro Max, iOS 16.1.2
![EF072628-9654-4BBF-B4A4-9C7F1D589631](https://user-images.githubusercontent.com/44187836/222724749-d43a2fae-7178-455d-ae88-f133e461299a.png)
![B532FCCE-A95C-447D-9BE5-49586DB66368](https://user-images.githubusercontent.com/44187836/222724631-e36c8532-fbde-4b55-bdcd-afcad823811b.png)

**Comment by bomberfish** [comment]
The capinfo certificate was revoked. This is not an issue I can fix.
