### ISSUE TITLE
Does it support checkm8 devices through temporary jailbreak?

### ISSUE THREAD

**Issue by i1itione** [BomberFish/Whitelist#8]
I have iPhone X (iOS 16.5.1) and iPhone 7 (iOS 15.7.8), they are able to be jailbroken very easily via palera1n, but the problem is the phones randomly reboot itself very often, then I need to re-jailbreak these iPhones again via PC. I just want to install some modified IPAs like uYouPlus, so I decide to change to use 3rd-Party store to install IPAs. My question is if my devices get blacklist issue, can I un-blacklist it through temporary jailbreak (remove the jailbreak enviroment afterward)?

**Comment by Newbietogithubb** [comment]
> I have iPhone X (iOS 16.5.1) and iPhone 7 (iOS 15.7.8), they are able to be jailbroken very easily via palera1n, but the problem is the phones randomly reboot itself very often, then I need to re-jailbreak these iPhones again via PC. I just want to install some modified IPAs like uYouPlus, so I decide to change to use 3rd-Party store to install IPAs. My question is if my devices get blacklist issue, can I un-blacklist it through temporary jailbreak (remove the jailbreak enviroment afterward)?

This only works on 16.1.2 max. Your iphone x is out of luck. And it got patched in 15.7.2. You’re out of luck. Sorry. It's best to just use jailbroken trollstore for perma ipa's.
