### ISSUE TITLE
[A10 CPU device] Not working - it doesn't asks for read/write access and cannot see the files

### ISSUE THREAD

**Issue by joeyoropesa-dev** [BomberFish/Whitelist#9]
![image](https://github.com/BomberFish/Whitelist/assets/45666011/cdbc8ad0-b45d-4def-81a3-8814d87a451f)![image](https://github.com/BomberFish/Whitelist/assets/45666011/8e0a8846-6f4b-402a-8663-6bcee02a43df)

I've installed it using latest TrollStore but for some reason, someday Blacklist ipa stopped to work - it stuck on reading - and now using this app I can see why it's stuck. My device is mdc compatible but not kfd compatible due to no offsets

So, what's the requirements of this tool and how can this be fixed

What actually could cause that problem - can Misaka cause that problem because the mdc is already been used by Misaka somehow or what's going on

I would appreciate the help and the fix by the dev of Whitelist/Blocklist app so I can use one of them normally and without permission problems.

At least, some code that will require on start to always give the read/write permissions on supported ios versions instead of not permission popups and permission errors

**Comment by bomberfish** [comment]
if you have trollstore this is not useful for you. i also stopped maintaining this a long time ago.
